/*
 Generated by typeshare 1.13.4
*/

export type Bitfield = string;

export enum Color {
	Black = "Black",
	White = "White",
}

export type ColorContainer<T> = [T, T];

export interface BoardData {
	player_color: Color;
	bitfield: ColorContainer<Bitfield>;
}

export type Board = BoardData;

export type ByteSize = number;

export type Depth = number;

export type Pos = string;

export type MaybePos = Pos | undefined;

export type History = MaybePos[];

export interface GameStateData {
	board: Board;
	history: History;
}

export type GameState = GameStateData;

export type HashKey = string;

export type PrincipalVariation = MaybePos[];

export type Score = number;

export interface DurationSchema {
	secs: number;
	nanos: number;
}

export interface BestMove {
	hash: HashKey;
	pos: MaybePos;
	score: Score;
	selective_depth: number;
	total_nodes_in_1k: number;
	time_elapsed: DurationSchema;
	pv: PrincipalVariation;
}

export interface ComputingResource {
	workers: number;
	tt_size: ByteSize;
	time: DurationSchema;
	nodes_in_1k?: number;
}

export enum RuleKind {
	Gomoku = "Gomoku",
	Renju = "Renju",
}

export interface Timer {
	total_remaining: DurationSchema;
	increment: DurationSchema;
	turn: DurationSchema;
}

export interface Config {
	rule_kind: RuleKind;
	draw_condition: number;
	max_nodes_in_1k: number;
	max_depth: Depth;
	max_vcf_depth: Depth;
	tt_size: ByteSize;
	workers: number;
	pondering: boolean;
	dynamic_time: boolean;
	initial_timer: Timer;
	spawn_depth_specialist: boolean;
}

export type Command = 
	| { type: "Clear", content?: undefined }
	| { type: "Play", content: MaybePos }
	| { type: "Set", content: {
	pos: Pos;
	color: Color;
}}
	| { type: "Unset", content: {
	pos: Pos;
	color: Color;
}}
	| { type: "Undo", content?: undefined }
	| { type: "BatchSet", content: {
	player_moves: Pos[];
	opponent_moves: Pos[];
}}
	| { type: "TurnTime", content: DurationSchema }
	| { type: "IncrementTime", content: DurationSchema }
	| { type: "TotalTime", content: DurationSchema }
	| { type: "ConsumeTime", content: DurationSchema }
	| { type: "Pondering", content: boolean }
	| { type: "MaxNodes", content: {
	in_1k: number;
}}
	| { type: "Workers", content: number }
	| { type: "MaxMemory", content: ByteSize }
	| { type: "Rule", content: RuleKind };

export type GameResult = 
	| { type: "Win", content: Color }
	| { type: "Draw", content?: undefined }
	| { type: "Full", content?: undefined };

export type Response = 
	| { type: "Begins", content: ComputingResource }
	| { type: "Status", content: {
	best_move: MaybePos;
	score: Score;
	pv: PrincipalVariation;
	total_nodes_in_1k: number;
	depth: Depth;
}}
	| { type: "Finished", content?: undefined };

export enum SearchObjective {
	Best = "Best",
	Zeroing = "Zeroing",
	Pondering = "Pondering",
}

